// This file will be auto-generated by `npx supabase gen types typescript`
// after Supabase is connected. For now it provides the type structure.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          date_of_birth: string | null
          height_cm: number | null
          weight_kg: number | null
          fitness_level: 'beginner' | 'intermediate' | 'advanced' | null
          subscription_tier: 'free' | 'plus'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          date_of_birth?: string | null
          height_cm?: number | null
          weight_kg?: number | null
          fitness_level?: 'beginner' | 'intermediate' | 'advanced' | null
          subscription_tier?: 'free' | 'plus'
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      goals: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          description: string | null
          target_date: string | null
          status: 'active' | 'completed' | 'paused'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          description?: string | null
          target_date?: string | null
          status?: 'active' | 'completed' | 'paused'
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['goals']['Insert']>
      }
      ai_usage_logs: {
        Row: {
          id: string
          user_id: string
          billing_period: string
          interaction_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          billing_period: string
          interaction_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['ai_usage_logs']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
